### ISSUE TITLE
Event Creation UI

### ISSUE THREAD

**Issue by sprintska** [Valadian/T4#11]
Implement a way to create events.

**Comment by sprintska** [comment]
Issue with getting Hasura to auto-populate the creator_id when user creates a tournament, and I haven't figured out why yet.

- I'm signed in, callbacks working correctly.
- The Hasura logs correctly show my user.sub in the x-hasura-user-id for the query.
- The Column Preset *appears* to be correctly set to autopopulate creator_id from x-hasura-user-id.  

Hope to get some more time to troubleshoot this tomorrow.

**Comment by Valadian** [comment]
Need verification that this works on yourside

**Comment by sprintska** [comment]
> It worked in dev

Yup, that cleared it up.  Super weird.
