### ISSUE TITLE
Make sure the event can be linked

### ISSUE THREAD

**Issue by sprintska** [Valadian/T4#27]
Was having an issue with refreshing the tourney homepage. In some of my research this issue also manifested as an inability to link slug-populated pages. Validate that this works and remediate if not.

**Comment by Valadian** [comment]
I don't have issues loading events from a url. Though I have seen JWT issues, which means being anonymous and being denied read permission on private tournament

**Comment by sprintska** [comment]
Just tested this--same error as the refreshing issue, which strengthens my suspicion it's related.  Picking up both since they're probably the same issue.

**Comment by sprintska** [comment]
Magically disappeared. /sigh

Closing this one as duplicate.  See #16
