### ISSUE TITLE
UI bug when editing event date

### ISSUE THREAD

**Issue by sprintska** [Valadian/T4#29]
When you change the event date in the AdminHeader, the DateEditor component pops "Loading..." under it and never clears.

**Comment by Tysolarius** [comment]
While in the perpetually loading state noted in the ticket description, the event date also cannot be changed again - it is stuck as whatever date it was changed to.

**Comment by Valadian** [comment]
fixed in d6b144f21cec02da4da21cec1acd4c8f9bc67a92
