### ISSUE TITLE
Need a way to add the Bye opponent back in

### ISSUE THREAD

**Issue by sprintska** [Valadian/T4#59]
If you delete a bye match, there's no way to get the bye opponent back.

Also would need an inexhaustible way to get multiple byes manually in case of something like the old FFGOP circuit, where a first-round bye to the next-higher tier of tourney was a prize for winning a lower-tier event, so you could have multiple byes in a round.

**Comment by Valadian** [comment]
you can click the + add match, and drag the player to the empty table, and
manually score them

**Comment by sprintska** [comment]
You can, but that feels like a workaround.  It doesn't display the same (opponent name isn't BYE), it's not recorded the same (opponent name isn't BYE), and it's not autocalculated.
